/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/mgmVmoGsVkf
 */
import Link from "next/link"

export function Site() {
  return (
    (<div className="dark min-h-screen bg-gray-900 text-gray-100">
      <header className="px-4 py-6 lg:px-8">
        <div className="container mx-auto flex justify-between items-center">
          <h1 className="text-2xl font-bold">Pyrex Sites</h1>
          <nav className="space-x-4">
            <Link className="hover:underline" href="#">
              Skills
            </Link>
            <Link className="hover:underline" href="#">
              Projects
            </Link>
            <Link className="hover:underline" href="#">
              Testimonials
            </Link>
          </nav>
        </div>
      </header>
      <main>
        <section className="py-12 lg:py-24">
          <div className="container mx-auto text-center">
            <h2 className="text-4xl font-bold mb-4">Building Quality Software</h2>
            <p className="text-lg text-gray-300 mb-8">Creating innovative solutions to solve modern problems</p>
            <Link
              className="inline-flex h-10 items-center justify-center rounded-md bg-purple-600 px-8 text-sm font-medium text-gray-50 shadow transition-colors hover:bg-purple-500"
              href="#">
              Contact Me
            </Link>
          </div>
        </section>
        <section className="py-12 lg:py-24 bg-gray-800" id="skills">
          <div className="container mx-auto grid gap-8 md:grid-cols-3 text-center">
            <div>
              <CodeIcon className="h-12 w-12 mx-auto mb-4 text-purple-500" />
              <h3 className="text-2xl font-bold mb-2">Desenvolvimento</h3>
              <p className="text-gray-300">Building scalable and maintainable software solutions.</p>
            </div>
            <div>
              <LayoutIcon className="h-12 w-12 mx-auto mb-4 text-purple-500" />
              <h3 className="text-2xl font-bold mb-2">Design</h3>
              <p className="text-gray-300">Creating intuitive and responsive user interfaces.</p>
            </div>
            <div>
              <DatabaseIcon className="h-12 w-12 mx-auto mb-4 text-purple-500" />
              <h3 className="text-2xl font-bold mb-2">Automações</h3>
              <p className="text-gray-300">Designing efficient and secure data storage solutions.</p>
            </div>
          </div>
        </section>
        <section className="py-12 lg:py-24" id="projects">
          <div className="container mx-auto text-center">
            <h2 className="text-4xl font-bold mb-8">Projects</h2>
            <p className="text-lg text-gray-300 mb-8">A showcase of my latest work</p>
            <Link
              className="inline-flex h-10 items-center justify-center rounded-md bg-purple-600 px-8 text-sm font-medium text-gray-50 shadow transition-colors hover:bg-purple-500"
              href="#">
              View Projects
            </Link>
          </div>
        </section>
        <section className="py-12 lg:py-24 bg-gray-800" id="testimonials">
          <div className="container mx-auto text-center">
            <h2 className="text-4xl font-bold mb-8">Testimonials</h2>
            <p className="text-lg text-gray-300 mb-8">What my clients are saying</p>
            <div className="grid gap-8 md:grid-cols-2 lg:grid-cols-3">
              <blockquote>
                <p className="text-gray-300 mb-4">"Great work, very responsive and professional."</p>
                <cite className="text-purple-500">- Client A</cite>
              </blockquote>
              <blockquote>
                <p className="text-gray-300 mb-4">"Delivered on time and exceeded expectations."</p>
                <cite className="text-purple-500">- Client B</cite>
              </blockquote>
              <blockquote>
                <p className="text-gray-300 mb-4">"Highly recommended for any software development needs."</p>
                <cite className="text-purple-500">- Client C</cite>
              </blockquote>
            </div>
          </div>
        </section>
      </main>
      <footer className="py-6 bg-gray-800">
        <div className="container mx-auto flex justify-between items-center">
          <div className="text-gray-300">© Software Developer</div>
          <div className="flex space-x-4">
            <Link className="text-gray-300 hover:text-purple-500" href="#">
              <TwitterIcon className="h-6 w-6" />
            </Link>
            <Link className="text-gray-300 hover:text-purple-500" href="#">
              <GithubIcon className="h-6 w-6" />
            </Link>
            <Link className="text-gray-300 hover:text-purple-500" href="#">
              <LinkedinIcon className="h-6 w-6" />
            </Link>
          </div>
        </div>
      </footer>
    </div>)
  );
}


function CodeIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <polyline points="16 18 22 12 16 6" />
      <polyline points="8 6 2 12 8 18" />
    </svg>)
  );
}


function LayoutIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <rect width="18" height="18" x="3" y="3" rx="2" ry="2" />
      <line x1="3" x2="21" y1="9" y2="9" />
      <line x1="9" x2="9" y1="21" y2="9" />
    </svg>)
  );
}


function DatabaseIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <ellipse cx="12" cy="5" rx="9" ry="3" />
      <path d="M3 5V19A9 3 0 0 0 21 19V5" />
      <path d="M3 12A9 3 0 0 0 21 12" />
    </svg>)
  );
}


function TwitterIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path
        d="M22 4s-.7 2.1-2 3.4c1.6 10-9.4 17.3-18 11.6 2.2.1 4.4-.6 6-2C3 15.5.5 9.6 3 5c2.2 2.6 5.6 4.1 9 4-.9-4.2 4-6.6 7-3.8 1.1 0 3-1.2 3-1.2z" />
    </svg>)
  );
}


function GithubIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path
        d="M15 22v-4a4.8 4.8 0 0 0-1-3.5c3 0 6-2 6-5.5.08-1.25-.27-2.48-1-3.5.28-1.15.28-2.35 0-3.5 0 0-1 0-3 1.5-2.64-.5-5.36-.5-8 0C6 2 5 2 5 2c-.3 1.15-.3 2.35 0 3.5A5.403 5.403 0 0 0 4 9c0 3.5 3 5.5 6 5.5-.39.49-.68 1.05-.85 1.65-.17.6-.22 1.23-.15 1.85v4" />
      <path d="M9 18c-4.51 2-5-2-7-2" />
    </svg>)
  );
}


function LinkedinIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path
        d="M16 8a6 6 0 0 1 6 6v7h-4v-7a2 2 0 0 0-2-2 2 2 0 0 0-2 2v7h-4v-7a6 6 0 0 1 6-6z" />
      <rect width="4" height="12" x="2" y="9" />
      <circle cx="4" cy="4" r="2" />
    </svg>)
  );
}
