/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/smFiXKLahIs
 */
import Link from "next/link"
import { FaLinkedinIn, FaGithub, FaInstagram, FaWhatsapp, FaCannabis, FaVoicemail } from "react-icons/fa"

const socialNetworks = [
  { name: "whatsapp", icon: <FaWhatsapp />, url: "https://api.whatsapp.com/send?phone=553299985779&text=Opa,%20quero%20fazer%20um%20or%C3%A7amento%20com%20a%20pyrex!" },
  { name: "instagram", icon: <FaInstagram />, url: "https://www.instagram.com/pyrexsites/" },
  
]

export function Template2() {
  return (
    (<div className="dark min-h-screen p-3 bg-gray-900 text-gray-100">
      <header className="px-4 py-1 lg:px-8">
        <div className="container mx-auto flex justify-between items-center">
          <div className="flex items-center">
            <ComputerIcon className="h-6 w-6 mr-3 text-blue-800" />
            <h1 className="text-2xl font-bold ">Pyrex Sites </h1>
          </div>

          <nav className="flex justify-center">
  <section className="flex items-center">
    {socialNetworks.map((network) => (
      <a
        href={network.url}
        className="h-10 w-1rem hover:text-blue-500 mx-2 text-2xl"  // Adicionei a classe text-xl para aumentar a fonte
        id={network.name}
        key={network.name}
      >
        {network.icon}
      </a>
    ))}
  </section>
</nav>
          
          
        </div>
      </header>
      <main>
        <section className="bg-gray-900" id="skills">
        <div className="container mx-auto text-center pt-20">
          <h1 className="text-3xl font-bold mb-4">Quem somos nós? 💙</h1>
             <h2 className="mb-3 text-xl"> A Pyrex é uma empresa de TI voltada na criação de Sites e Software para empresas e pessoas!</h2>
                <h2 className="mb-3 pb-4 text-xl" >Sempre fazendo sites responsivos e com a melhor experiência para seu usuário!</h2>
                <Link
              className="inline-flex h-10 items-center justify-center rounded-md bg-blue-800 px-8 text-sm font-medium text-gray-50 shadow transition-colors hover:bg-blue-800"
              href="https://gustavokurtz.github.io/">
              Projetos
            </Link>
        </div>
          <div className="container mx-auto grid gap-8 md:grid-cols-3 text-center pt-20">
            <div>
              <CodeIcon className="h-12 w-12 mx-auto mb-4 text-blue-800" />
              <h3 className="text-2xl font-bold mb-2">Sites</h3>
              <p className="text-gray-300">Construindo sites personalizados do jeito que o cliente quer!.</p>
            </div>
            <div>
              <LayoutIcon className="h-12 w-12 mx-auto mb-4 text-blue-800" />
              <h3 className="text-2xl font-bold mb-2">Lojas Virtuais</h3>
              <p className="text-gray-300">Criando lojas virtuais para qualquer tipo de empreendimento!.</p>
            </div>
            <div>
              <DatabaseIcon className="h-12 w-12 mx-auto mb-4 text-blue-800" />
              <h3 className="text-2xl font-bold mb-2">Tráfego Pago</h3>
              <p className="text-gray-300">Sempre levando muitos clientes para sua empresa ou produto! </p>
            </div>
          </div>
          <section className="py-12 lg:py-24">
          <div className="container mx-auto text-center">
            <h2 className="text-2xl font-bold mb-4">Construindo Software de Qualidade</h2>
            <p className="text-lg text-gray-300 mb-8">Criando soluções inovadoras para resolver problemas modernos</p>
            <Link
              className="inline-flex h-10 items-center justify-center rounded-md bg-blue-800 px-8 text-sm font-medium text-gray-50 shadow transition-colors hover:bg-blue-800"
              href="https://api.whatsapp.com/send?phone=553299985779&text=Opa,%20quero%20fazer%20um%20or%C3%A7amento%20com%20a%20pyrex!">
              Fale Conosco
            </Link>
          </div>
        </section>
        </section>
      </main>
    </div>)
  );
}


function ComputerIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <rect width="14" height="8" x="5" y="2" rx="2" />
      <rect width="20" height="8" x="2" y="14" rx="2" />
      <path d="M6 18h2" />
      <path d="M12 18h6" />
    </svg>)
  );
}


function CodeIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <polyline points="16 18 22 12 16 6" />
      <polyline points="8 6 2 12 8 18" />
    </svg>)
  );
}


function LayoutIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <rect width="18" height="18" x="3" y="3" rx="2" ry="2" />
      <line x1="3" x2="21" y1="9" y2="9" />
      <line x1="9" x2="9" y1="21" y2="9" />
    </svg>)
  );
}


function DatabaseIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <ellipse cx="12" cy="5" rx="9" ry="3" />
      <path d="M3 5V19A9 3 0 0 0 21 19V5" />
      <path d="M3 12A9 3 0 0 0 21 12" />
    </svg>)
  );
}


function TwitterIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path
        d="M22 4s-.7 2.1-2 3.4c1.6 10-9.4 17.3-18 11.6 2.2.1 4.4-.6 6-2C3 15.5.5 9.6 3 5c2.2 2.6 5.6 4.1 9 4-.9-4.2 4-6.6 7-3.8 1.1 0 3-1.2 3-1.2z" />
    </svg>)
  );
}


function GithubIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path
        d="M15 22v-4a4.8 4.8 0 0 0-1-3.5c3 0 6-2 6-5.5.08-1.25-.27-2.48-1-3.5.28-1.15.28-2.35 0-3.5 0 0-1 0-3 1.5-2.64-.5-5.36-.5-8 0C6 2 5 2 5 2c-.3 1.15-.3 2.35 0 3.5A5.403 5.403 0 0 0 4 9c0 3.5 3 5.5 6 5.5-.39.49-.68 1.05-.85 1.65-.17.6-.22 1.23-.15 1.85v4" />
      <path d="M9 18c-4.51 2-5-2-7-2" />
    </svg>)
  );
}


function SmartphoneIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <rect width="14" height="20" x="5" y="2" rx="2" ry="2" />
      <path d="M12 18h.01" />
    </svg>)
  );
}

